// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2832.PracticeRobotCode;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Relay;
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Relay motorRelayMotorRelay1;
    public static CANTalon lFront;
    public static CANTalon rFront;
    public static CANTalon lRear;
    public static CANTalon rRear;
    public static RobotDrive driveSystem;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        motorRelayMotorRelay1 = new Relay(0);
        LiveWindow.addActuator("MotorRelay", "MotorRelay1", motorRelayMotorRelay1);

        lFront = new CANTalon(1);
        LiveWindow.addActuator("Wheels", "Speed Controller 1", (CANTalon) lFront);
        
        rFront = new CANTalon(3);
        LiveWindow.addActuator("Wheels", "Speed Controller 2", (CANTalon) rFront);
        
        lRear = new CANTalon(2);
        LiveWindow.addActuator("Wheels", "Speed Controller 3", (CANTalon) lRear);
        
        rRear = new CANTalon(4);
        LiveWindow.addActuator("Wheels", "Speed Controller 4", (CANTalon) rRear);
        
        driveSystem = new RobotDrive(lFront, lRear,
              rFront, rRear);
        
        driveSystem.setSafetyEnabled(true);
        driveSystem.setExpiration(0.1);
        driveSystem.setSensitivity(0.5);
        driveSystem.setMaxOutput(1.0);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
